const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'index.html'), 'utf8');
const appJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'app.js'), 'utf8');
const todoJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'todo.js'), 'utf8');
const themeJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'theme.js'), 'utf8');
const stylesCss = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'styles.css'), 'utf8');
const notificationHtml = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'notification.html'), 'utf8');
const notificationJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'notification.js'), 'utf8');
const workspaceJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'workspace.js'), 'utf8');
const effectsJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'effects.js'), 'utf8');
const strongReminderHtml = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'strong-reminder.html'), 'utf8');
const strongReminderJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'strong-reminder.js'), 'utf8');
const desktopCardHtml = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'desktop-card.html'), 'utf8');
const desktopCardJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'desktop-card.js'), 'utf8');
const mainJs = fs.readFileSync(path.join(__dirname, '..', 'main.js'), 'utf8');
const preloadJs = fs.readFileSync(path.join(__dirname, '..', 'preload.js'), 'utf8');

test('legacy product modules are removed from user-facing tabs and panels', () => {
  for (const tab of ['notes', 'links', 'recordings', 'credentials', 'clip']) {
    assert.doesNotMatch(html, new RegExp(`data-tab="${tab}"`));
    assert.doesNotMatch(html, new RegExp(`id="tab-${tab}"`));
  }
});

test('todo page exposes smart views, hierarchy, details, reminders, and subtasks', () => {
  assert.match(html, /id="todo-smart-nav"/);
  assert.match(html, /id="todo-list-tree"/);
  assert.match(html, /id="todo-task-list"/);
  assert.match(html, /id="todo-detail-form"/);
  assert.match(html, /id="todo-reminder-presets"/);
  assert.match(html, /data-reminder-offset="0"/);
  assert.match(html, /data-reminder-offset="1"/);
  assert.match(html, /id="todo-subtask-list"/);
  assert.match(html, /id="todo-quick-preview"/);
  assert.match(html, /id="todo-sort-toggle"/);
  assert.match(html, /id="todo-detail-pin"/);
  assert.match(html, /id="todo-list-default-reminders"/);
  assert.match(html, /id="todo-picker-grid"/);
  assert.match(html, /data-todo-view="calendar"/);
  assert.match(html, /data-todo-view="blocked"/);
  assert.match(html, /data-todo-view="history"/);
  assert.match(html, /data-todo-view="trash"/);
  assert.match(html, /id="todo-missed-policy"/);
  assert.match(html, /id="todo-template-select"/);
  assert.match(html, /id="todo-detail-recurrence"/);
  assert.match(html, /id="todo-backup-now"/);
  assert.match(html, /id="todo-shortcut-hints"/);
  assert.match(html, /id="todo-detail-strong-reminder"/);
  assert.match(html, /id="todo-detail-strong-reminder-at"/);
  assert.match(html, /id="todo-detail-state"/);
  assert.match(html, /id="todo-block-dialog"/);
  assert.match(html, /id="todo-block-reason-options"/);
  assert.match(html, /id="todo-block-reason"/);
  assert.match(html, /id="todo-block-next-action"/);
  assert.match(html, /id="todo-export-dialog"/);
  assert.match(html, /id="todo-export-scope"/);
  assert.match(html, /id="todo-export-format"/);
  assert.match(html, /id="todo-export-include-completed"/);
  assert.match(html, /id="todo-export-include-activity"/);
  assert.match(html, /id="todo-detail-desktop-card"/);
  assert.match(html, /id="todo-siri-import"/);
  assert.match(html, /id="siri-import-dialog"/);
  assert.match(html, /id="siri-import-reminder-list"/);
  assert.match(html, /id="siri-import-target-list"/);
  assert.match(html, /id="strong-reminder-warning"/);
  assert.match(html, /id="strong-reminder-warning-step"/);
  assert.match(html, /id="strong-reminder-time-step"/);
  assert.match(html, /data-strong-reminder-time="same"/);
  assert.match(html, /data-strong-reminder-time="10"/);
  assert.match(html, /data-strong-reminder-time="30"/);
  assert.match(html, /data-strong-reminder-time="60"/);
  assert.match(html, /data-strong-reminder-time="custom"/);
  assert.match(html, /id="strong-reminder-custom-at"/);
  assert.match(html, /id="settings-strong-question-0"/);
  assert.match(html, /id="settings-strong-question-1"/);
  assert.match(html, /id="settings-daily-review-enabled"/);
  assert.match(html, /id="settings-daily-review-time"/);
  assert.match(html, /id="settings-notification-duration"/);
  assert.match(html, /id="todo-activity-toggle"/);
  assert.match(html, /id="daily-review-backdrop"/);
  assert.match(todoJs, /normalizeTodoWorkspace/);
  assert.match(todoJs, /filterTodoTasks/);
  assert.match(todoJs, /scheduleTodoReminders/);
  assert.match(todoJs, /parseTodoQuickInput/);
  assert.match(todoJs, /reorderTodoTasks/);
  assert.match(todoJs, /todo-inline-subtasks/);
  assert.match(todoJs, /openTodoPicker/);
  assert.match(todoJs, /renderCalendarView/);
  assert.match(todoJs, /createNextTodoOccurrence/);
  assert.match(todoJs, /restoreTrashTask/);
  assert.match(todoJs, /backupTodoData/);
  assert.match(todoJs, /notch-todo-data-v1-backup/);
  assert.match(todoJs, /onStrongReminderResolved/);
  assert.match(todoJs, /unhandledReminderAt/);
  assert.match(todoJs, /todo-unhandled-badge/);
  assert.match(todoJs, /onTodoReminderHandled/);
  assert.match(todoJs, /setStrongReminderQuestions/);
  assert.match(todoJs, /detailStart,\s*detailDeadline,\s*detailStrongReminderAt,/);
  assert.match(todoJs, /strongReminderLinked/);
  assert.match(todoJs, /strongReminderCustomAt/);
  assert.match(todoJs, /scheduleDailyReview/);
  assert.match(todoJs, /rescheduleTaskFromDailyReview/);
  assert.match(todoJs, /openBlockDialog/);
  assert.match(todoJs, /submitExportReport/);
  assert.match(todoJs, /reportScopeData/);
  assert.match(todoJs, /desktopCardPayload/);
  assert.match(todoJs, /addDesktopCardFromDrop/);
  assert.match(todoJs, /importSiriReminders/);
  assert.match(todoJs, /listReminderItems/);
  assert.match(todoJs, /showSiriImportFeedback/);
  assert.match(todoJs, /siriImportRunning/);
  assert.match(workspaceJs, /setDailyReviewSettings/);
  assert.match(workspaceJs, /setTodoNotificationDuration/);
  assert.match(workspaceJs, /renderNotificationDurationNote/);
  assert.match(stylesCss, /todo-activity-list/);
  assert.match(appJs, /todoShortcutHints\.hidden = name !== 'todo'/);
  assert.match(notificationHtml, /id="notification-snooze"/);
  assert.match(notificationJs, /snoozeTodoReminder/);
  assert.match(notificationJs, /markTaskNotificationHandled/);
  assert.match(strongReminderHtml, /strong-root/);
  assert.match(strongReminderHtml, /id="strong-deadline-toggle"/);
  assert.match(strongReminderHtml, /id="strong-date-picker"/);
  assert.match(strongReminderHtml, /id="strong-picker-grid"/);
  assert.doesNotMatch(strongReminderHtml, /type="datetime-local"/);
  assert.match(strongReminderJs, /resolveStrongReminder/);
  assert.match(strongReminderJs, /ANSWER_OPTIONS/);
  assert.match(strongReminderJs, /custom_extend/);
  assert.match(strongReminderJs, /openDeadlinePicker/);
  assert.match(strongReminderJs, /emergencyExit/);
  assert.match(mainJs, /strong-reminder:abort/);
  assert.match(mainJs, /completionConfirmed: payload\?\.completionConfirmed === true/);
  assert.match(preloadJs, /abortStrongReminder/);
  assert.match(preloadJs, /exportTodoReport/);
  assert.match(preloadJs, /syncDesktopCards/);
  assert.match(preloadJs, /setTodoNotificationDuration/);
  assert.match(preloadJs, /onTodoReminderHandled/);
  assert.match(preloadJs, /listReminderLists/);
  assert.match(preloadJs, /listReminderItems/);
  assert.doesNotMatch(preloadJs, /VoiceRecognition|VoiceTodo/);
  assert.doesNotMatch(html, /voice-todo|todo-voice-add/);
  assert.doesNotMatch(todoJs, /VoiceRecognition|VoiceTodo|parseVoiceTranscript/);
  assert.match(mainJs, /todos:export-report/);
  assert.match(mainJs, /createTodoReportPdf/);
  assert.match(mainJs, /reconcileDesktopCards/);
  assert.match(mainJs, /desktop-card:set-always-on-top/);
  assert.match(mainJs, /reminders:lists/);
  assert.match(mainJs, /reminders:items/);
  assert.match(mainJs, /ensureRemindersRunning/);
  assert.match(mainJs, /'-g', '-j', '-a', 'Reminders'/);
  assert.match(mainJs, /settings:set-todo-notification-duration/);
  assert.match(mainJs, /taskNotificationPersistent/);
  assert.doesNotMatch(mainJs, /VOICE_TODO_SHORTCUT|voice-recognition:start|speech-helper/);
  assert.match(desktopCardHtml, /id="desktop-card"/);
  assert.match(desktopCardJs, /desktopCardAPI/);
  assert.match(html, /叮做/);
  assert.match(mainJs, /build', 'dingdo-icon\.png'/);
  assert.match(notificationHtml, /assets\/app-logo-128\.png/);
});

test('home focuses on system media and today summary', () => {
  assert.match(html, /id="home-focus-layout"/);
  assert.match(html, /id="music-artwork"/);
  assert.match(html, /id="music-artist"/);
  assert.match(html, /id="home-today-summary"/);
  assert.match(html, /id="home-today-list"/);
  assert.match(workspaceJs, /refreshMusicStatus/);
  assert.match(workspaceJs, /renderHomeToday/);
  assert.match(html, /id="music-seek"/);
  assert.match(html, /id="music-volume"/);
  assert.match(html, /id="settings-theme-grid"/);
  assert.match(html, /id="settings-browser-media"/);
  assert.match(themeJs, /notch-appearance-v1/);
  assert.match(themeJs, /browserMedia/);
  assert.match(stylesCss, /--date-input-text/);
  assert.match(stylesCss, /todo-unhandled-pulse/);
  assert.match(stylesCss, /\[data-todo-date-input\]/);
  assert.match(stylesCss, /--picker-selected-bg/);
  assert.match(html, /id="notch-media"/);
  assert.match(html, /id="notch-eyes"/);
  assert.match(html, /id="notch-mouth"/);
  assert.match(html, /id="notch-peek"/);
  assert.match(stylesCss, /--notch-width:\s*280px/);
  assert.match(stylesCss, /--notch-inset/);
  assert.match(stylesCss, /notch-eq/);
  assert.match(workspaceJs, /applyCollapsedMediaStatus/);
  assert.match(workspaceJs, /scheduleEyeGaze/);
  assert.match(workspaceJs, /showStatusPeek/);
  assert.match(workspaceJs, /showPeek: showStatusPeek/);
  assert.match(stylesCss, /notch-mouth-cycle/);
  assert.match(stylesCss, /data-preview-kind='siri'/);
  assert.match(workspaceJs, /collapsed \? 4500 : 0/);
});

test('homepage visibility has one storage key, exact validation, and lifecycle events', () => {
  assert.match(appJs, /notch-home-hidden-modules-v1/);
  assert.match(appJs, /validateHomeWidgetLayout/);
  assert.match(appJs, /window\.NotchHome\s*=/);
  assert.match(appJs, /notch:home-modules-changed/);
  assert.match(appJs, /notch:home-layout-error/);
  assert.match(appJs, /stopMirror\(\)/);
  assert.match(appJs, /new Set\(homeTiles\.map\(\(tile\) => tile\.dataset\.homeModule\)\)/);
});

test('obsolete settings surfaces stay hidden', () => {
  assert.match(html, /settings-api-card" hidden/);
  assert.match(html, /settings-features-card" hidden/);
  assert.match(html, /settings-home-modules-card" hidden/);
  assert.match(html, /settings-mirror-card" hidden/);
});

test('settings exposes every panel tab as a possible default opening page', () => {
  const select = html.match(/<select id="settings-default-tab"[\s\S]*?<\/select>/)?.[0] || '';
  const options = [...select.matchAll(/<option value="([^"]+)"/g)].map((match) => match[1]);
  assert.deepEqual(options, [
    'home', 'todo', 'settings',
  ]);
  assert.match(workspaceJs, /setDefaultTab/);
});

test('hidden visual widgets stop presentation-only background work', () => {
  assert.match(effectsJs, /setEnabled/);
  assert.match(effectsJs, /notch:home-modules-changed/);
  assert.match(workspaceJs, /NotchHome\?\.isVisible/);
});
